package pv.dotai.datai.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connectionless_netmessages.proto

public final class ConnectionlessNetmessages {
  private ConnectionlessNetmessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface C2S_CONNECT_MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C2S_CONNECT_Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 host_version = 1;</code>
     */
    boolean hasHostVersion();
    /**
     * <code>optional uint32 host_version = 1;</code>
     */
    int getHostVersion();

    /**
     * <code>optional uint32 auth_protocol = 2;</code>
     */
    boolean hasAuthProtocol();
    /**
     * <code>optional uint32 auth_protocol = 2;</code>
     */
    int getAuthProtocol();

    /**
     * <code>optional uint32 challenge_number = 3;</code>
     */
    boolean hasChallengeNumber();
    /**
     * <code>optional uint32 challenge_number = 3;</code>
     */
    int getChallengeNumber();

    /**
     * <code>optional fixed64 reservation_cookie = 4;</code>
     */
    boolean hasReservationCookie();
    /**
     * <code>optional fixed64 reservation_cookie = 4;</code>
     */
    long getReservationCookie();

    /**
     * <code>optional bool low_violence = 5;</code>
     */
    boolean hasLowViolence();
    /**
     * <code>optional bool low_violence = 5;</code>
     */
    boolean getLowViolence();

    /**
     * <code>optional bytes encrypted_password = 6;</code>
     */
    boolean hasEncryptedPassword();
    /**
     * <code>optional bytes encrypted_password = 6;</code>
     */
    com.google.protobuf.ByteString getEncryptedPassword();

    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    java.util.List<Netmessages.CCLCMsg_SplitPlayerConnect> 
        getSplitplayersList();
    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    Netmessages.CCLCMsg_SplitPlayerConnect getSplitplayers(int index);
    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    int getSplitplayersCount();
    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    java.util.List<? extends Netmessages.CCLCMsg_SplitPlayerConnectOrBuilder> 
        getSplitplayersOrBuilderList();
    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    Netmessages.CCLCMsg_SplitPlayerConnectOrBuilder getSplitplayersOrBuilder(
        int index);

    /**
     * <code>optional bytes auth_steam = 8;</code>
     */
    boolean hasAuthSteam();
    /**
     * <code>optional bytes auth_steam = 8;</code>
     */
    com.google.protobuf.ByteString getAuthSteam();

    /**
     * <code>optional string challenge_context = 9;</code>
     */
    boolean hasChallengeContext();
    /**
     * <code>optional string challenge_context = 9;</code>
     */
    java.lang.String getChallengeContext();
    /**
     * <code>optional string challenge_context = 9;</code>
     */
    com.google.protobuf.ByteString
        getChallengeContextBytes();
  }
  /**
   * Protobuf type {@code C2S_CONNECT_Message}
   */
  public  static final class C2S_CONNECT_Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C2S_CONNECT_Message)
      C2S_CONNECT_MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_CONNECT_Message.newBuilder() to construct.
    private C2S_CONNECT_Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_CONNECT_Message() {
      hostVersion_ = 0;
      authProtocol_ = 0;
      challengeNumber_ = 0;
      reservationCookie_ = 0L;
      lowViolence_ = false;
      encryptedPassword_ = com.google.protobuf.ByteString.EMPTY;
      splitplayers_ = java.util.Collections.emptyList();
      authSteam_ = com.google.protobuf.ByteString.EMPTY;
      challengeContext_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_CONNECT_Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hostVersion_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              authProtocol_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              challengeNumber_ = input.readUInt32();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              reservationCookie_ = input.readFixed64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              lowViolence_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              encryptedPassword_ = input.readBytes();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                splitplayers_ = new java.util.ArrayList<Netmessages.CCLCMsg_SplitPlayerConnect>();
                mutable_bitField0_ |= 0x00000040;
              }
              splitplayers_.add(
                  input.readMessage(Netmessages.CCLCMsg_SplitPlayerConnect.PARSER, extensionRegistry));
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              authSteam_ = input.readBytes();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              challengeContext_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          splitplayers_ = java.util.Collections.unmodifiableList(splitplayers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConnectionlessNetmessages.internal_static_C2S_CONNECT_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConnectionlessNetmessages.internal_static_C2S_CONNECT_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ConnectionlessNetmessages.C2S_CONNECT_Message.class, ConnectionlessNetmessages.C2S_CONNECT_Message.Builder.class);
    }

    private int bitField0_;
    public static final int HOST_VERSION_FIELD_NUMBER = 1;
    private int hostVersion_;
    /**
     * <code>optional uint32 host_version = 1;</code>
     */
    public boolean hasHostVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 host_version = 1;</code>
     */
    public int getHostVersion() {
      return hostVersion_;
    }

    public static final int AUTH_PROTOCOL_FIELD_NUMBER = 2;
    private int authProtocol_;
    /**
     * <code>optional uint32 auth_protocol = 2;</code>
     */
    public boolean hasAuthProtocol() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 auth_protocol = 2;</code>
     */
    public int getAuthProtocol() {
      return authProtocol_;
    }

    public static final int CHALLENGE_NUMBER_FIELD_NUMBER = 3;
    private int challengeNumber_;
    /**
     * <code>optional uint32 challenge_number = 3;</code>
     */
    public boolean hasChallengeNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 challenge_number = 3;</code>
     */
    public int getChallengeNumber() {
      return challengeNumber_;
    }

    public static final int RESERVATION_COOKIE_FIELD_NUMBER = 4;
    private long reservationCookie_;
    /**
     * <code>optional fixed64 reservation_cookie = 4;</code>
     */
    public boolean hasReservationCookie() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional fixed64 reservation_cookie = 4;</code>
     */
    public long getReservationCookie() {
      return reservationCookie_;
    }

    public static final int LOW_VIOLENCE_FIELD_NUMBER = 5;
    private boolean lowViolence_;
    /**
     * <code>optional bool low_violence = 5;</code>
     */
    public boolean hasLowViolence() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool low_violence = 5;</code>
     */
    public boolean getLowViolence() {
      return lowViolence_;
    }

    public static final int ENCRYPTED_PASSWORD_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString encryptedPassword_;
    /**
     * <code>optional bytes encrypted_password = 6;</code>
     */
    public boolean hasEncryptedPassword() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes encrypted_password = 6;</code>
     */
    public com.google.protobuf.ByteString getEncryptedPassword() {
      return encryptedPassword_;
    }

    public static final int SPLITPLAYERS_FIELD_NUMBER = 7;
    private java.util.List<Netmessages.CCLCMsg_SplitPlayerConnect> splitplayers_;
    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    public java.util.List<Netmessages.CCLCMsg_SplitPlayerConnect> getSplitplayersList() {
      return splitplayers_;
    }
    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    public java.util.List<? extends Netmessages.CCLCMsg_SplitPlayerConnectOrBuilder> 
        getSplitplayersOrBuilderList() {
      return splitplayers_;
    }
    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    public int getSplitplayersCount() {
      return splitplayers_.size();
    }
    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    public Netmessages.CCLCMsg_SplitPlayerConnect getSplitplayers(int index) {
      return splitplayers_.get(index);
    }
    /**
     * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
     */
    public Netmessages.CCLCMsg_SplitPlayerConnectOrBuilder getSplitplayersOrBuilder(
        int index) {
      return splitplayers_.get(index);
    }

    public static final int AUTH_STEAM_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString authSteam_;
    /**
     * <code>optional bytes auth_steam = 8;</code>
     */
    public boolean hasAuthSteam() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes auth_steam = 8;</code>
     */
    public com.google.protobuf.ByteString getAuthSteam() {
      return authSteam_;
    }

    public static final int CHALLENGE_CONTEXT_FIELD_NUMBER = 9;
    private volatile java.lang.Object challengeContext_;
    /**
     * <code>optional string challenge_context = 9;</code>
     */
    public boolean hasChallengeContext() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string challenge_context = 9;</code>
     */
    public java.lang.String getChallengeContext() {
      java.lang.Object ref = challengeContext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          challengeContext_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string challenge_context = 9;</code>
     */
    public com.google.protobuf.ByteString
        getChallengeContextBytes() {
      java.lang.Object ref = challengeContext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        challengeContext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, hostVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, authProtocol_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, challengeNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed64(4, reservationCookie_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, lowViolence_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, encryptedPassword_);
      }
      for (int i = 0; i < splitplayers_.size(); i++) {
        output.writeMessage(7, splitplayers_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, authSteam_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, challengeContext_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, hostVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, authProtocol_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, challengeNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(4, reservationCookie_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, lowViolence_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, encryptedPassword_);
      }
      for (int i = 0; i < splitplayers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, splitplayers_.get(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, authSteam_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, challengeContext_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ConnectionlessNetmessages.C2S_CONNECT_Message)) {
        return super.equals(obj);
      }
      ConnectionlessNetmessages.C2S_CONNECT_Message other = (ConnectionlessNetmessages.C2S_CONNECT_Message) obj;

      boolean result = true;
      result = result && (hasHostVersion() == other.hasHostVersion());
      if (hasHostVersion()) {
        result = result && (getHostVersion()
            == other.getHostVersion());
      }
      result = result && (hasAuthProtocol() == other.hasAuthProtocol());
      if (hasAuthProtocol()) {
        result = result && (getAuthProtocol()
            == other.getAuthProtocol());
      }
      result = result && (hasChallengeNumber() == other.hasChallengeNumber());
      if (hasChallengeNumber()) {
        result = result && (getChallengeNumber()
            == other.getChallengeNumber());
      }
      result = result && (hasReservationCookie() == other.hasReservationCookie());
      if (hasReservationCookie()) {
        result = result && (getReservationCookie()
            == other.getReservationCookie());
      }
      result = result && (hasLowViolence() == other.hasLowViolence());
      if (hasLowViolence()) {
        result = result && (getLowViolence()
            == other.getLowViolence());
      }
      result = result && (hasEncryptedPassword() == other.hasEncryptedPassword());
      if (hasEncryptedPassword()) {
        result = result && getEncryptedPassword()
            .equals(other.getEncryptedPassword());
      }
      result = result && getSplitplayersList()
          .equals(other.getSplitplayersList());
      result = result && (hasAuthSteam() == other.hasAuthSteam());
      if (hasAuthSteam()) {
        result = result && getAuthSteam()
            .equals(other.getAuthSteam());
      }
      result = result && (hasChallengeContext() == other.hasChallengeContext());
      if (hasChallengeContext()) {
        result = result && getChallengeContext()
            .equals(other.getChallengeContext());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHostVersion()) {
        hash = (37 * hash) + HOST_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getHostVersion();
      }
      if (hasAuthProtocol()) {
        hash = (37 * hash) + AUTH_PROTOCOL_FIELD_NUMBER;
        hash = (53 * hash) + getAuthProtocol();
      }
      if (hasChallengeNumber()) {
        hash = (37 * hash) + CHALLENGE_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getChallengeNumber();
      }
      if (hasReservationCookie()) {
        hash = (37 * hash) + RESERVATION_COOKIE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getReservationCookie());
      }
      if (hasLowViolence()) {
        hash = (37 * hash) + LOW_VIOLENCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getLowViolence());
      }
      if (hasEncryptedPassword()) {
        hash = (37 * hash) + ENCRYPTED_PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedPassword().hashCode();
      }
      if (getSplitplayersCount() > 0) {
        hash = (37 * hash) + SPLITPLAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getSplitplayersList().hashCode();
      }
      if (hasAuthSteam()) {
        hash = (37 * hash) + AUTH_STEAM_FIELD_NUMBER;
        hash = (53 * hash) + getAuthSteam().hashCode();
      }
      if (hasChallengeContext()) {
        hash = (37 * hash) + CHALLENGE_CONTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getChallengeContext().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ConnectionlessNetmessages.C2S_CONNECT_Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ConnectionlessNetmessages.C2S_CONNECT_Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2S_CONNECT_Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C2S_CONNECT_Message)
        ConnectionlessNetmessages.C2S_CONNECT_MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ConnectionlessNetmessages.internal_static_C2S_CONNECT_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ConnectionlessNetmessages.internal_static_C2S_CONNECT_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ConnectionlessNetmessages.C2S_CONNECT_Message.class, ConnectionlessNetmessages.C2S_CONNECT_Message.Builder.class);
      }

      // Construct using ConnectionlessNetmessages.C2S_CONNECT_Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSplitplayersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        hostVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        authProtocol_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        challengeNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        reservationCookie_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        lowViolence_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        encryptedPassword_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (splitplayersBuilder_ == null) {
          splitplayers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          splitplayersBuilder_.clear();
        }
        authSteam_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        challengeContext_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ConnectionlessNetmessages.internal_static_C2S_CONNECT_Message_descriptor;
      }

      public ConnectionlessNetmessages.C2S_CONNECT_Message getDefaultInstanceForType() {
        return ConnectionlessNetmessages.C2S_CONNECT_Message.getDefaultInstance();
      }

      public ConnectionlessNetmessages.C2S_CONNECT_Message build() {
        ConnectionlessNetmessages.C2S_CONNECT_Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ConnectionlessNetmessages.C2S_CONNECT_Message buildPartial() {
        ConnectionlessNetmessages.C2S_CONNECT_Message result = new ConnectionlessNetmessages.C2S_CONNECT_Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hostVersion_ = hostVersion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.authProtocol_ = authProtocol_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.challengeNumber_ = challengeNumber_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.reservationCookie_ = reservationCookie_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lowViolence_ = lowViolence_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.encryptedPassword_ = encryptedPassword_;
        if (splitplayersBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            splitplayers_ = java.util.Collections.unmodifiableList(splitplayers_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.splitplayers_ = splitplayers_;
        } else {
          result.splitplayers_ = splitplayersBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.authSteam_ = authSteam_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.challengeContext_ = challengeContext_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConnectionlessNetmessages.C2S_CONNECT_Message) {
          return mergeFrom((ConnectionlessNetmessages.C2S_CONNECT_Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ConnectionlessNetmessages.C2S_CONNECT_Message other) {
        if (other == ConnectionlessNetmessages.C2S_CONNECT_Message.getDefaultInstance()) return this;
        if (other.hasHostVersion()) {
          setHostVersion(other.getHostVersion());
        }
        if (other.hasAuthProtocol()) {
          setAuthProtocol(other.getAuthProtocol());
        }
        if (other.hasChallengeNumber()) {
          setChallengeNumber(other.getChallengeNumber());
        }
        if (other.hasReservationCookie()) {
          setReservationCookie(other.getReservationCookie());
        }
        if (other.hasLowViolence()) {
          setLowViolence(other.getLowViolence());
        }
        if (other.hasEncryptedPassword()) {
          setEncryptedPassword(other.getEncryptedPassword());
        }
        if (splitplayersBuilder_ == null) {
          if (!other.splitplayers_.isEmpty()) {
            if (splitplayers_.isEmpty()) {
              splitplayers_ = other.splitplayers_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureSplitplayersIsMutable();
              splitplayers_.addAll(other.splitplayers_);
            }
            onChanged();
          }
        } else {
          if (!other.splitplayers_.isEmpty()) {
            if (splitplayersBuilder_.isEmpty()) {
              splitplayersBuilder_.dispose();
              splitplayersBuilder_ = null;
              splitplayers_ = other.splitplayers_;
              bitField0_ = (bitField0_ & ~0x00000040);
              splitplayersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSplitplayersFieldBuilder() : null;
            } else {
              splitplayersBuilder_.addAllMessages(other.splitplayers_);
            }
          }
        }
        if (other.hasAuthSteam()) {
          setAuthSteam(other.getAuthSteam());
        }
        if (other.hasChallengeContext()) {
          bitField0_ |= 0x00000100;
          challengeContext_ = other.challengeContext_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ConnectionlessNetmessages.C2S_CONNECT_Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ConnectionlessNetmessages.C2S_CONNECT_Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int hostVersion_ ;
      /**
       * <code>optional uint32 host_version = 1;</code>
       */
      public boolean hasHostVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 host_version = 1;</code>
       */
      public int getHostVersion() {
        return hostVersion_;
      }
      /**
       * <code>optional uint32 host_version = 1;</code>
       */
      public Builder setHostVersion(int value) {
        bitField0_ |= 0x00000001;
        hostVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 host_version = 1;</code>
       */
      public Builder clearHostVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hostVersion_ = 0;
        onChanged();
        return this;
      }

      private int authProtocol_ ;
      /**
       * <code>optional uint32 auth_protocol = 2;</code>
       */
      public boolean hasAuthProtocol() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 auth_protocol = 2;</code>
       */
      public int getAuthProtocol() {
        return authProtocol_;
      }
      /**
       * <code>optional uint32 auth_protocol = 2;</code>
       */
      public Builder setAuthProtocol(int value) {
        bitField0_ |= 0x00000002;
        authProtocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 auth_protocol = 2;</code>
       */
      public Builder clearAuthProtocol() {
        bitField0_ = (bitField0_ & ~0x00000002);
        authProtocol_ = 0;
        onChanged();
        return this;
      }

      private int challengeNumber_ ;
      /**
       * <code>optional uint32 challenge_number = 3;</code>
       */
      public boolean hasChallengeNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 challenge_number = 3;</code>
       */
      public int getChallengeNumber() {
        return challengeNumber_;
      }
      /**
       * <code>optional uint32 challenge_number = 3;</code>
       */
      public Builder setChallengeNumber(int value) {
        bitField0_ |= 0x00000004;
        challengeNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 challenge_number = 3;</code>
       */
      public Builder clearChallengeNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        challengeNumber_ = 0;
        onChanged();
        return this;
      }

      private long reservationCookie_ ;
      /**
       * <code>optional fixed64 reservation_cookie = 4;</code>
       */
      public boolean hasReservationCookie() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional fixed64 reservation_cookie = 4;</code>
       */
      public long getReservationCookie() {
        return reservationCookie_;
      }
      /**
       * <code>optional fixed64 reservation_cookie = 4;</code>
       */
      public Builder setReservationCookie(long value) {
        bitField0_ |= 0x00000008;
        reservationCookie_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 reservation_cookie = 4;</code>
       */
      public Builder clearReservationCookie() {
        bitField0_ = (bitField0_ & ~0x00000008);
        reservationCookie_ = 0L;
        onChanged();
        return this;
      }

      private boolean lowViolence_ ;
      /**
       * <code>optional bool low_violence = 5;</code>
       */
      public boolean hasLowViolence() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool low_violence = 5;</code>
       */
      public boolean getLowViolence() {
        return lowViolence_;
      }
      /**
       * <code>optional bool low_violence = 5;</code>
       */
      public Builder setLowViolence(boolean value) {
        bitField0_ |= 0x00000010;
        lowViolence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool low_violence = 5;</code>
       */
      public Builder clearLowViolence() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lowViolence_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encryptedPassword_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes encrypted_password = 6;</code>
       */
      public boolean hasEncryptedPassword() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes encrypted_password = 6;</code>
       */
      public com.google.protobuf.ByteString getEncryptedPassword() {
        return encryptedPassword_;
      }
      /**
       * <code>optional bytes encrypted_password = 6;</code>
       */
      public Builder setEncryptedPassword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        encryptedPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes encrypted_password = 6;</code>
       */
      public Builder clearEncryptedPassword() {
        bitField0_ = (bitField0_ & ~0x00000020);
        encryptedPassword_ = getDefaultInstance().getEncryptedPassword();
        onChanged();
        return this;
      }

      private java.util.List<Netmessages.CCLCMsg_SplitPlayerConnect> splitplayers_ =
        java.util.Collections.emptyList();
      private void ensureSplitplayersIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          splitplayers_ = new java.util.ArrayList<Netmessages.CCLCMsg_SplitPlayerConnect>(splitplayers_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Netmessages.CCLCMsg_SplitPlayerConnect, Netmessages.CCLCMsg_SplitPlayerConnect.Builder, Netmessages.CCLCMsg_SplitPlayerConnectOrBuilder> splitplayersBuilder_;

      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public java.util.List<Netmessages.CCLCMsg_SplitPlayerConnect> getSplitplayersList() {
        if (splitplayersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(splitplayers_);
        } else {
          return splitplayersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public int getSplitplayersCount() {
        if (splitplayersBuilder_ == null) {
          return splitplayers_.size();
        } else {
          return splitplayersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Netmessages.CCLCMsg_SplitPlayerConnect getSplitplayers(int index) {
        if (splitplayersBuilder_ == null) {
          return splitplayers_.get(index);
        } else {
          return splitplayersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Builder setSplitplayers(
          int index, Netmessages.CCLCMsg_SplitPlayerConnect value) {
        if (splitplayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSplitplayersIsMutable();
          splitplayers_.set(index, value);
          onChanged();
        } else {
          splitplayersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Builder setSplitplayers(
          int index, Netmessages.CCLCMsg_SplitPlayerConnect.Builder builderForValue) {
        if (splitplayersBuilder_ == null) {
          ensureSplitplayersIsMutable();
          splitplayers_.set(index, builderForValue.build());
          onChanged();
        } else {
          splitplayersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Builder addSplitplayers(Netmessages.CCLCMsg_SplitPlayerConnect value) {
        if (splitplayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSplitplayersIsMutable();
          splitplayers_.add(value);
          onChanged();
        } else {
          splitplayersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Builder addSplitplayers(
          int index, Netmessages.CCLCMsg_SplitPlayerConnect value) {
        if (splitplayersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSplitplayersIsMutable();
          splitplayers_.add(index, value);
          onChanged();
        } else {
          splitplayersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Builder addSplitplayers(
          Netmessages.CCLCMsg_SplitPlayerConnect.Builder builderForValue) {
        if (splitplayersBuilder_ == null) {
          ensureSplitplayersIsMutable();
          splitplayers_.add(builderForValue.build());
          onChanged();
        } else {
          splitplayersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Builder addSplitplayers(
          int index, Netmessages.CCLCMsg_SplitPlayerConnect.Builder builderForValue) {
        if (splitplayersBuilder_ == null) {
          ensureSplitplayersIsMutable();
          splitplayers_.add(index, builderForValue.build());
          onChanged();
        } else {
          splitplayersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Builder addAllSplitplayers(
          java.lang.Iterable<? extends Netmessages.CCLCMsg_SplitPlayerConnect> values) {
        if (splitplayersBuilder_ == null) {
          ensureSplitplayersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, splitplayers_);
          onChanged();
        } else {
          splitplayersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Builder clearSplitplayers() {
        if (splitplayersBuilder_ == null) {
          splitplayers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          splitplayersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Builder removeSplitplayers(int index) {
        if (splitplayersBuilder_ == null) {
          ensureSplitplayersIsMutable();
          splitplayers_.remove(index);
          onChanged();
        } else {
          splitplayersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Netmessages.CCLCMsg_SplitPlayerConnect.Builder getSplitplayersBuilder(
          int index) {
        return getSplitplayersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Netmessages.CCLCMsg_SplitPlayerConnectOrBuilder getSplitplayersOrBuilder(
          int index) {
        if (splitplayersBuilder_ == null) {
          return splitplayers_.get(index);  } else {
          return splitplayersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public java.util.List<? extends Netmessages.CCLCMsg_SplitPlayerConnectOrBuilder> 
           getSplitplayersOrBuilderList() {
        if (splitplayersBuilder_ != null) {
          return splitplayersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(splitplayers_);
        }
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Netmessages.CCLCMsg_SplitPlayerConnect.Builder addSplitplayersBuilder() {
        return getSplitplayersFieldBuilder().addBuilder(
            Netmessages.CCLCMsg_SplitPlayerConnect.getDefaultInstance());
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public Netmessages.CCLCMsg_SplitPlayerConnect.Builder addSplitplayersBuilder(
          int index) {
        return getSplitplayersFieldBuilder().addBuilder(
            index, Netmessages.CCLCMsg_SplitPlayerConnect.getDefaultInstance());
      }
      /**
       * <code>repeated .CCLCMsg_SplitPlayerConnect splitplayers = 7;</code>
       */
      public java.util.List<Netmessages.CCLCMsg_SplitPlayerConnect.Builder> 
           getSplitplayersBuilderList() {
        return getSplitplayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Netmessages.CCLCMsg_SplitPlayerConnect, Netmessages.CCLCMsg_SplitPlayerConnect.Builder, Netmessages.CCLCMsg_SplitPlayerConnectOrBuilder> 
          getSplitplayersFieldBuilder() {
        if (splitplayersBuilder_ == null) {
          splitplayersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Netmessages.CCLCMsg_SplitPlayerConnect, Netmessages.CCLCMsg_SplitPlayerConnect.Builder, Netmessages.CCLCMsg_SplitPlayerConnectOrBuilder>(
                  splitplayers_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          splitplayers_ = null;
        }
        return splitplayersBuilder_;
      }

      private com.google.protobuf.ByteString authSteam_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes auth_steam = 8;</code>
       */
      public boolean hasAuthSteam() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes auth_steam = 8;</code>
       */
      public com.google.protobuf.ByteString getAuthSteam() {
        return authSteam_;
      }
      /**
       * <code>optional bytes auth_steam = 8;</code>
       */
      public Builder setAuthSteam(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        authSteam_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes auth_steam = 8;</code>
       */
      public Builder clearAuthSteam() {
        bitField0_ = (bitField0_ & ~0x00000080);
        authSteam_ = getDefaultInstance().getAuthSteam();
        onChanged();
        return this;
      }

      private java.lang.Object challengeContext_ = "";
      /**
       * <code>optional string challenge_context = 9;</code>
       */
      public boolean hasChallengeContext() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string challenge_context = 9;</code>
       */
      public java.lang.String getChallengeContext() {
        java.lang.Object ref = challengeContext_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            challengeContext_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string challenge_context = 9;</code>
       */
      public com.google.protobuf.ByteString
          getChallengeContextBytes() {
        java.lang.Object ref = challengeContext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          challengeContext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string challenge_context = 9;</code>
       */
      public Builder setChallengeContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        challengeContext_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string challenge_context = 9;</code>
       */
      public Builder clearChallengeContext() {
        bitField0_ = (bitField0_ & ~0x00000100);
        challengeContext_ = getDefaultInstance().getChallengeContext();
        onChanged();
        return this;
      }
      /**
       * <code>optional string challenge_context = 9;</code>
       */
      public Builder setChallengeContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        challengeContext_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C2S_CONNECT_Message)
    }

    // @@protoc_insertion_point(class_scope:C2S_CONNECT_Message)
    private static final ConnectionlessNetmessages.C2S_CONNECT_Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ConnectionlessNetmessages.C2S_CONNECT_Message();
    }

    public static ConnectionlessNetmessages.C2S_CONNECT_Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_CONNECT_Message>
        PARSER = new com.google.protobuf.AbstractParser<C2S_CONNECT_Message>() {
      public C2S_CONNECT_Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2S_CONNECT_Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_CONNECT_Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_CONNECT_Message> getParserForType() {
      return PARSER;
    }

    public ConnectionlessNetmessages.C2S_CONNECT_Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface C2S_CONNECTION_MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:C2S_CONNECTION_Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string addon_name = 1;</code>
     */
    boolean hasAddonName();
    /**
     * <code>optional string addon_name = 1;</code>
     */
    java.lang.String getAddonName();
    /**
     * <code>optional string addon_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddonNameBytes();
  }
  /**
   * Protobuf type {@code C2S_CONNECTION_Message}
   */
  public  static final class C2S_CONNECTION_Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:C2S_CONNECTION_Message)
      C2S_CONNECTION_MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use C2S_CONNECTION_Message.newBuilder() to construct.
    private C2S_CONNECTION_Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private C2S_CONNECTION_Message() {
      addonName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private C2S_CONNECTION_Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              addonName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConnectionlessNetmessages.internal_static_C2S_CONNECTION_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConnectionlessNetmessages.internal_static_C2S_CONNECTION_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ConnectionlessNetmessages.C2S_CONNECTION_Message.class, ConnectionlessNetmessages.C2S_CONNECTION_Message.Builder.class);
    }

    private int bitField0_;
    public static final int ADDON_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object addonName_;
    /**
     * <code>optional string addon_name = 1;</code>
     */
    public boolean hasAddonName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string addon_name = 1;</code>
     */
    public java.lang.String getAddonName() {
      java.lang.Object ref = addonName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          addonName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string addon_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddonNameBytes() {
      java.lang.Object ref = addonName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addonName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addonName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addonName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ConnectionlessNetmessages.C2S_CONNECTION_Message)) {
        return super.equals(obj);
      }
      ConnectionlessNetmessages.C2S_CONNECTION_Message other = (ConnectionlessNetmessages.C2S_CONNECTION_Message) obj;

      boolean result = true;
      result = result && (hasAddonName() == other.hasAddonName());
      if (hasAddonName()) {
        result = result && getAddonName()
            .equals(other.getAddonName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAddonName()) {
        hash = (37 * hash) + ADDON_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getAddonName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ConnectionlessNetmessages.C2S_CONNECTION_Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ConnectionlessNetmessages.C2S_CONNECTION_Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code C2S_CONNECTION_Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:C2S_CONNECTION_Message)
        ConnectionlessNetmessages.C2S_CONNECTION_MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ConnectionlessNetmessages.internal_static_C2S_CONNECTION_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ConnectionlessNetmessages.internal_static_C2S_CONNECTION_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ConnectionlessNetmessages.C2S_CONNECTION_Message.class, ConnectionlessNetmessages.C2S_CONNECTION_Message.Builder.class);
      }

      // Construct using ConnectionlessNetmessages.C2S_CONNECTION_Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        addonName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ConnectionlessNetmessages.internal_static_C2S_CONNECTION_Message_descriptor;
      }

      public ConnectionlessNetmessages.C2S_CONNECTION_Message getDefaultInstanceForType() {
        return ConnectionlessNetmessages.C2S_CONNECTION_Message.getDefaultInstance();
      }

      public ConnectionlessNetmessages.C2S_CONNECTION_Message build() {
        ConnectionlessNetmessages.C2S_CONNECTION_Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ConnectionlessNetmessages.C2S_CONNECTION_Message buildPartial() {
        ConnectionlessNetmessages.C2S_CONNECTION_Message result = new ConnectionlessNetmessages.C2S_CONNECTION_Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.addonName_ = addonName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ConnectionlessNetmessages.C2S_CONNECTION_Message) {
          return mergeFrom((ConnectionlessNetmessages.C2S_CONNECTION_Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ConnectionlessNetmessages.C2S_CONNECTION_Message other) {
        if (other == ConnectionlessNetmessages.C2S_CONNECTION_Message.getDefaultInstance()) return this;
        if (other.hasAddonName()) {
          bitField0_ |= 0x00000001;
          addonName_ = other.addonName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ConnectionlessNetmessages.C2S_CONNECTION_Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ConnectionlessNetmessages.C2S_CONNECTION_Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object addonName_ = "";
      /**
       * <code>optional string addon_name = 1;</code>
       */
      public boolean hasAddonName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string addon_name = 1;</code>
       */
      public java.lang.String getAddonName() {
        java.lang.Object ref = addonName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            addonName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string addon_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddonNameBytes() {
        java.lang.Object ref = addonName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addonName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string addon_name = 1;</code>
       */
      public Builder setAddonName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        addonName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string addon_name = 1;</code>
       */
      public Builder clearAddonName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        addonName_ = getDefaultInstance().getAddonName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string addon_name = 1;</code>
       */
      public Builder setAddonNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        addonName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:C2S_CONNECTION_Message)
    }

    // @@protoc_insertion_point(class_scope:C2S_CONNECTION_Message)
    private static final ConnectionlessNetmessages.C2S_CONNECTION_Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ConnectionlessNetmessages.C2S_CONNECTION_Message();
    }

    public static ConnectionlessNetmessages.C2S_CONNECTION_Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<C2S_CONNECTION_Message>
        PARSER = new com.google.protobuf.AbstractParser<C2S_CONNECTION_Message>() {
      public C2S_CONNECTION_Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new C2S_CONNECTION_Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<C2S_CONNECTION_Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2S_CONNECTION_Message> getParserForType() {
      return PARSER;
    }

    public ConnectionlessNetmessages.C2S_CONNECTION_Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C2S_CONNECT_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C2S_CONNECT_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_C2S_CONNECTION_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_C2S_CONNECTION_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n connectionless_netmessages.proto\032\021netm" +
      "essages.proto\"\214\002\n\023C2S_CONNECT_Message\022\024\n" +
      "\014host_version\030\001 \001(\r\022\025\n\rauth_protocol\030\002 \001" +
      "(\r\022\030\n\020challenge_number\030\003 \001(\r\022\032\n\022reservat" +
      "ion_cookie\030\004 \001(\006\022\024\n\014low_violence\030\005 \001(\010\022\032" +
      "\n\022encrypted_password\030\006 \001(\014\0221\n\014splitplaye" +
      "rs\030\007 \003(\0132\033.CCLCMsg_SplitPlayerConnect\022\022\n" +
      "\nauth_steam\030\010 \001(\014\022\031\n\021challenge_context\030\t" +
      " \001(\t\",\n\026C2S_CONNECTION_Message\022\022\n\naddon_" +
      "name\030\001 \001(\tB\003\200\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Netmessages.getDescriptor(),
        }, assigner);
    internal_static_C2S_CONNECT_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_C2S_CONNECT_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C2S_CONNECT_Message_descriptor,
        new java.lang.String[] { "HostVersion", "AuthProtocol", "ChallengeNumber", "ReservationCookie", "LowViolence", "EncryptedPassword", "Splitplayers", "AuthSteam", "ChallengeContext", });
    internal_static_C2S_CONNECTION_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_C2S_CONNECTION_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_C2S_CONNECTION_Message_descriptor,
        new java.lang.String[] { "AddonName", });
    Netmessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
