package pv.dotai.datai.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c_peer2peer_netmessages.proto

public final class CPeer2PeerNetmessages {
  private CPeer2PeerNetmessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code P2P_Messages}
   */
  public enum P2P_Messages
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>p2p_TextMessage = 256;</code>
     */
    p2p_TextMessage(256),
    /**
     * <code>p2p_Voice = 257;</code>
     */
    p2p_Voice(257),
    /**
     * <code>p2p_Ping = 258;</code>
     */
    p2p_Ping(258),
    ;

    /**
     * <code>p2p_TextMessage = 256;</code>
     */
    public static final int p2p_TextMessage_VALUE = 256;
    /**
     * <code>p2p_Voice = 257;</code>
     */
    public static final int p2p_Voice_VALUE = 257;
    /**
     * <code>p2p_Ping = 258;</code>
     */
    public static final int p2p_Ping_VALUE = 258;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static P2P_Messages valueOf(int value) {
      return forNumber(value);
    }

    public static P2P_Messages forNumber(int value) {
      switch (value) {
        case 256: return p2p_TextMessage;
        case 257: return p2p_Voice;
        case 258: return p2p_Ping;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<P2P_Messages>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        P2P_Messages> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<P2P_Messages>() {
            public P2P_Messages findValueByNumber(int number) {
              return P2P_Messages.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CPeer2PeerNetmessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final P2P_Messages[] VALUES = values();

    public static P2P_Messages valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private P2P_Messages(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:P2P_Messages)
  }

  public interface CP2P_TextMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CP2P_TextMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>optional bytes text = 1;</code>
     */
    com.google.protobuf.ByteString getText();
  }
  /**
   * Protobuf type {@code CP2P_TextMessage}
   */
  public  static final class CP2P_TextMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CP2P_TextMessage)
      CP2P_TextMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CP2P_TextMessage.newBuilder() to construct.
    private CP2P_TextMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CP2P_TextMessage() {
      text_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CP2P_TextMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CPeer2PeerNetmessages.internal_static_CP2P_TextMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CPeer2PeerNetmessages.internal_static_CP2P_TextMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CPeer2PeerNetmessages.CP2P_TextMessage.class, CPeer2PeerNetmessages.CP2P_TextMessage.Builder.class);
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString text_;
    /**
     * <code>optional bytes text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes text = 1;</code>
     */
    public com.google.protobuf.ByteString getText() {
      return text_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, text_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, text_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CPeer2PeerNetmessages.CP2P_TextMessage)) {
        return super.equals(obj);
      }
      CPeer2PeerNetmessages.CP2P_TextMessage other = (CPeer2PeerNetmessages.CP2P_TextMessage) obj;

      boolean result = true;
      result = result && (hasText() == other.hasText());
      if (hasText()) {
        result = result && getText()
            .equals(other.getText());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasText()) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CP2P_TextMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CPeer2PeerNetmessages.CP2P_TextMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CP2P_TextMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CP2P_TextMessage)
        CPeer2PeerNetmessages.CP2P_TextMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CPeer2PeerNetmessages.internal_static_CP2P_TextMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CPeer2PeerNetmessages.internal_static_CP2P_TextMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CPeer2PeerNetmessages.CP2P_TextMessage.class, CPeer2PeerNetmessages.CP2P_TextMessage.Builder.class);
      }

      // Construct using CPeer2PeerNetmessages.CP2P_TextMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        text_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CPeer2PeerNetmessages.internal_static_CP2P_TextMessage_descriptor;
      }

      public CPeer2PeerNetmessages.CP2P_TextMessage getDefaultInstanceForType() {
        return CPeer2PeerNetmessages.CP2P_TextMessage.getDefaultInstance();
      }

      public CPeer2PeerNetmessages.CP2P_TextMessage build() {
        CPeer2PeerNetmessages.CP2P_TextMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CPeer2PeerNetmessages.CP2P_TextMessage buildPartial() {
        CPeer2PeerNetmessages.CP2P_TextMessage result = new CPeer2PeerNetmessages.CP2P_TextMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CPeer2PeerNetmessages.CP2P_TextMessage) {
          return mergeFrom((CPeer2PeerNetmessages.CP2P_TextMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CPeer2PeerNetmessages.CP2P_TextMessage other) {
        if (other == CPeer2PeerNetmessages.CP2P_TextMessage.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CPeer2PeerNetmessages.CP2P_TextMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CPeer2PeerNetmessages.CP2P_TextMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString text_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes text = 1;</code>
       */
      public com.google.protobuf.ByteString getText() {
        return text_;
      }
      /**
       * <code>optional bytes text = 1;</code>
       */
      public Builder setText(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CP2P_TextMessage)
    }

    // @@protoc_insertion_point(class_scope:CP2P_TextMessage)
    private static final CPeer2PeerNetmessages.CP2P_TextMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CPeer2PeerNetmessages.CP2P_TextMessage();
    }

    public static CPeer2PeerNetmessages.CP2P_TextMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CP2P_TextMessage>
        PARSER = new com.google.protobuf.AbstractParser<CP2P_TextMessage>() {
      public CP2P_TextMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CP2P_TextMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CP2P_TextMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CP2P_TextMessage> getParserForType() {
      return PARSER;
    }

    public CPeer2PeerNetmessages.CP2P_TextMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CSteam_Voice_EncodingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CSteam_Voice_Encoding)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes voice_data = 1;</code>
     */
    boolean hasVoiceData();
    /**
     * <code>optional bytes voice_data = 1;</code>
     */
    com.google.protobuf.ByteString getVoiceData();
  }
  /**
   * Protobuf type {@code CSteam_Voice_Encoding}
   */
  public  static final class CSteam_Voice_Encoding extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CSteam_Voice_Encoding)
      CSteam_Voice_EncodingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSteam_Voice_Encoding.newBuilder() to construct.
    private CSteam_Voice_Encoding(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSteam_Voice_Encoding() {
      voiceData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSteam_Voice_Encoding(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              voiceData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CPeer2PeerNetmessages.internal_static_CSteam_Voice_Encoding_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CPeer2PeerNetmessages.internal_static_CSteam_Voice_Encoding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CPeer2PeerNetmessages.CSteam_Voice_Encoding.class, CPeer2PeerNetmessages.CSteam_Voice_Encoding.Builder.class);
    }

    private int bitField0_;
    public static final int VOICE_DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString voiceData_;
    /**
     * <code>optional bytes voice_data = 1;</code>
     */
    public boolean hasVoiceData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes voice_data = 1;</code>
     */
    public com.google.protobuf.ByteString getVoiceData() {
      return voiceData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, voiceData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, voiceData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CPeer2PeerNetmessages.CSteam_Voice_Encoding)) {
        return super.equals(obj);
      }
      CPeer2PeerNetmessages.CSteam_Voice_Encoding other = (CPeer2PeerNetmessages.CSteam_Voice_Encoding) obj;

      boolean result = true;
      result = result && (hasVoiceData() == other.hasVoiceData());
      if (hasVoiceData()) {
        result = result && getVoiceData()
            .equals(other.getVoiceData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVoiceData()) {
        hash = (37 * hash) + VOICE_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getVoiceData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CPeer2PeerNetmessages.CSteam_Voice_Encoding prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CSteam_Voice_Encoding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CSteam_Voice_Encoding)
        CPeer2PeerNetmessages.CSteam_Voice_EncodingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CPeer2PeerNetmessages.internal_static_CSteam_Voice_Encoding_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CPeer2PeerNetmessages.internal_static_CSteam_Voice_Encoding_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CPeer2PeerNetmessages.CSteam_Voice_Encoding.class, CPeer2PeerNetmessages.CSteam_Voice_Encoding.Builder.class);
      }

      // Construct using CPeer2PeerNetmessages.CSteam_Voice_Encoding.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        voiceData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CPeer2PeerNetmessages.internal_static_CSteam_Voice_Encoding_descriptor;
      }

      public CPeer2PeerNetmessages.CSteam_Voice_Encoding getDefaultInstanceForType() {
        return CPeer2PeerNetmessages.CSteam_Voice_Encoding.getDefaultInstance();
      }

      public CPeer2PeerNetmessages.CSteam_Voice_Encoding build() {
        CPeer2PeerNetmessages.CSteam_Voice_Encoding result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CPeer2PeerNetmessages.CSteam_Voice_Encoding buildPartial() {
        CPeer2PeerNetmessages.CSteam_Voice_Encoding result = new CPeer2PeerNetmessages.CSteam_Voice_Encoding(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.voiceData_ = voiceData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CPeer2PeerNetmessages.CSteam_Voice_Encoding) {
          return mergeFrom((CPeer2PeerNetmessages.CSteam_Voice_Encoding)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CPeer2PeerNetmessages.CSteam_Voice_Encoding other) {
        if (other == CPeer2PeerNetmessages.CSteam_Voice_Encoding.getDefaultInstance()) return this;
        if (other.hasVoiceData()) {
          setVoiceData(other.getVoiceData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CPeer2PeerNetmessages.CSteam_Voice_Encoding parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CPeer2PeerNetmessages.CSteam_Voice_Encoding) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString voiceData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes voice_data = 1;</code>
       */
      public boolean hasVoiceData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes voice_data = 1;</code>
       */
      public com.google.protobuf.ByteString getVoiceData() {
        return voiceData_;
      }
      /**
       * <code>optional bytes voice_data = 1;</code>
       */
      public Builder setVoiceData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        voiceData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes voice_data = 1;</code>
       */
      public Builder clearVoiceData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        voiceData_ = getDefaultInstance().getVoiceData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CSteam_Voice_Encoding)
    }

    // @@protoc_insertion_point(class_scope:CSteam_Voice_Encoding)
    private static final CPeer2PeerNetmessages.CSteam_Voice_Encoding DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CPeer2PeerNetmessages.CSteam_Voice_Encoding();
    }

    public static CPeer2PeerNetmessages.CSteam_Voice_Encoding getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CSteam_Voice_Encoding>
        PARSER = new com.google.protobuf.AbstractParser<CSteam_Voice_Encoding>() {
      public CSteam_Voice_Encoding parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CSteam_Voice_Encoding(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSteam_Voice_Encoding> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSteam_Voice_Encoding> getParserForType() {
      return PARSER;
    }

    public CPeer2PeerNetmessages.CSteam_Voice_Encoding getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CP2P_VoiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CP2P_Voice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .CMsgVoiceAudio audio = 1;</code>
     */
    boolean hasAudio();
    /**
     * <code>optional .CMsgVoiceAudio audio = 1;</code>
     */
    Netmessages.CMsgVoiceAudio getAudio();
    /**
     * <code>optional .CMsgVoiceAudio audio = 1;</code>
     */
    Netmessages.CMsgVoiceAudioOrBuilder getAudioOrBuilder();

    /**
     * <code>optional uint32 broadcast_group = 2;</code>
     */
    boolean hasBroadcastGroup();
    /**
     * <code>optional uint32 broadcast_group = 2;</code>
     */
    int getBroadcastGroup();
  }
  /**
   * Protobuf type {@code CP2P_Voice}
   */
  public  static final class CP2P_Voice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CP2P_Voice)
      CP2P_VoiceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CP2P_Voice.newBuilder() to construct.
    private CP2P_Voice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CP2P_Voice() {
      broadcastGroup_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CP2P_Voice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Netmessages.CMsgVoiceAudio.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = audio_.toBuilder();
              }
              audio_ = input.readMessage(Netmessages.CMsgVoiceAudio.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(audio_);
                audio_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              broadcastGroup_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CPeer2PeerNetmessages.internal_static_CP2P_Voice_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CPeer2PeerNetmessages.internal_static_CP2P_Voice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CPeer2PeerNetmessages.CP2P_Voice.class, CPeer2PeerNetmessages.CP2P_Voice.Builder.class);
    }

    /**
     * Protobuf enum {@code CP2P_Voice.Handler_Flags}
     */
    public enum Handler_Flags
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Played_Audio = 1;</code>
       */
      Played_Audio(1),
      ;

      /**
       * <code>Played_Audio = 1;</code>
       */
      public static final int Played_Audio_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Handler_Flags valueOf(int value) {
        return forNumber(value);
      }

      public static Handler_Flags forNumber(int value) {
        switch (value) {
          case 1: return Played_Audio;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Handler_Flags>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Handler_Flags> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Handler_Flags>() {
              public Handler_Flags findValueByNumber(int number) {
                return Handler_Flags.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return CPeer2PeerNetmessages.CP2P_Voice.getDescriptor().getEnumTypes().get(0);
      }

      private static final Handler_Flags[] VALUES = values();

      public static Handler_Flags valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Handler_Flags(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CP2P_Voice.Handler_Flags)
    }

    private int bitField0_;
    public static final int AUDIO_FIELD_NUMBER = 1;
    private Netmessages.CMsgVoiceAudio audio_;
    /**
     * <code>optional .CMsgVoiceAudio audio = 1;</code>
     */
    public boolean hasAudio() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .CMsgVoiceAudio audio = 1;</code>
     */
    public Netmessages.CMsgVoiceAudio getAudio() {
      return audio_ == null ? Netmessages.CMsgVoiceAudio.getDefaultInstance() : audio_;
    }
    /**
     * <code>optional .CMsgVoiceAudio audio = 1;</code>
     */
    public Netmessages.CMsgVoiceAudioOrBuilder getAudioOrBuilder() {
      return audio_ == null ? Netmessages.CMsgVoiceAudio.getDefaultInstance() : audio_;
    }

    public static final int BROADCAST_GROUP_FIELD_NUMBER = 2;
    private int broadcastGroup_;
    /**
     * <code>optional uint32 broadcast_group = 2;</code>
     */
    public boolean hasBroadcastGroup() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 broadcast_group = 2;</code>
     */
    public int getBroadcastGroup() {
      return broadcastGroup_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getAudio());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, broadcastGroup_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getAudio());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, broadcastGroup_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CPeer2PeerNetmessages.CP2P_Voice)) {
        return super.equals(obj);
      }
      CPeer2PeerNetmessages.CP2P_Voice other = (CPeer2PeerNetmessages.CP2P_Voice) obj;

      boolean result = true;
      result = result && (hasAudio() == other.hasAudio());
      if (hasAudio()) {
        result = result && getAudio()
            .equals(other.getAudio());
      }
      result = result && (hasBroadcastGroup() == other.hasBroadcastGroup());
      if (hasBroadcastGroup()) {
        result = result && (getBroadcastGroup()
            == other.getBroadcastGroup());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAudio()) {
        hash = (37 * hash) + AUDIO_FIELD_NUMBER;
        hash = (53 * hash) + getAudio().hashCode();
      }
      if (hasBroadcastGroup()) {
        hash = (37 * hash) + BROADCAST_GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getBroadcastGroup();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CP2P_Voice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CPeer2PeerNetmessages.CP2P_Voice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CP2P_Voice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CP2P_Voice)
        CPeer2PeerNetmessages.CP2P_VoiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CPeer2PeerNetmessages.internal_static_CP2P_Voice_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CPeer2PeerNetmessages.internal_static_CP2P_Voice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CPeer2PeerNetmessages.CP2P_Voice.class, CPeer2PeerNetmessages.CP2P_Voice.Builder.class);
      }

      // Construct using CPeer2PeerNetmessages.CP2P_Voice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAudioFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (audioBuilder_ == null) {
          audio_ = null;
        } else {
          audioBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        broadcastGroup_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CPeer2PeerNetmessages.internal_static_CP2P_Voice_descriptor;
      }

      public CPeer2PeerNetmessages.CP2P_Voice getDefaultInstanceForType() {
        return CPeer2PeerNetmessages.CP2P_Voice.getDefaultInstance();
      }

      public CPeer2PeerNetmessages.CP2P_Voice build() {
        CPeer2PeerNetmessages.CP2P_Voice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CPeer2PeerNetmessages.CP2P_Voice buildPartial() {
        CPeer2PeerNetmessages.CP2P_Voice result = new CPeer2PeerNetmessages.CP2P_Voice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (audioBuilder_ == null) {
          result.audio_ = audio_;
        } else {
          result.audio_ = audioBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.broadcastGroup_ = broadcastGroup_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CPeer2PeerNetmessages.CP2P_Voice) {
          return mergeFrom((CPeer2PeerNetmessages.CP2P_Voice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CPeer2PeerNetmessages.CP2P_Voice other) {
        if (other == CPeer2PeerNetmessages.CP2P_Voice.getDefaultInstance()) return this;
        if (other.hasAudio()) {
          mergeAudio(other.getAudio());
        }
        if (other.hasBroadcastGroup()) {
          setBroadcastGroup(other.getBroadcastGroup());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CPeer2PeerNetmessages.CP2P_Voice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CPeer2PeerNetmessages.CP2P_Voice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Netmessages.CMsgVoiceAudio audio_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Netmessages.CMsgVoiceAudio, Netmessages.CMsgVoiceAudio.Builder, Netmessages.CMsgVoiceAudioOrBuilder> audioBuilder_;
      /**
       * <code>optional .CMsgVoiceAudio audio = 1;</code>
       */
      public boolean hasAudio() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .CMsgVoiceAudio audio = 1;</code>
       */
      public Netmessages.CMsgVoiceAudio getAudio() {
        if (audioBuilder_ == null) {
          return audio_ == null ? Netmessages.CMsgVoiceAudio.getDefaultInstance() : audio_;
        } else {
          return audioBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CMsgVoiceAudio audio = 1;</code>
       */
      public Builder setAudio(Netmessages.CMsgVoiceAudio value) {
        if (audioBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          audio_ = value;
          onChanged();
        } else {
          audioBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CMsgVoiceAudio audio = 1;</code>
       */
      public Builder setAudio(
          Netmessages.CMsgVoiceAudio.Builder builderForValue) {
        if (audioBuilder_ == null) {
          audio_ = builderForValue.build();
          onChanged();
        } else {
          audioBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CMsgVoiceAudio audio = 1;</code>
       */
      public Builder mergeAudio(Netmessages.CMsgVoiceAudio value) {
        if (audioBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              audio_ != null &&
              audio_ != Netmessages.CMsgVoiceAudio.getDefaultInstance()) {
            audio_ =
              Netmessages.CMsgVoiceAudio.newBuilder(audio_).mergeFrom(value).buildPartial();
          } else {
            audio_ = value;
          }
          onChanged();
        } else {
          audioBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CMsgVoiceAudio audio = 1;</code>
       */
      public Builder clearAudio() {
        if (audioBuilder_ == null) {
          audio_ = null;
          onChanged();
        } else {
          audioBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .CMsgVoiceAudio audio = 1;</code>
       */
      public Netmessages.CMsgVoiceAudio.Builder getAudioBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getAudioFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CMsgVoiceAudio audio = 1;</code>
       */
      public Netmessages.CMsgVoiceAudioOrBuilder getAudioOrBuilder() {
        if (audioBuilder_ != null) {
          return audioBuilder_.getMessageOrBuilder();
        } else {
          return audio_ == null ?
              Netmessages.CMsgVoiceAudio.getDefaultInstance() : audio_;
        }
      }
      /**
       * <code>optional .CMsgVoiceAudio audio = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Netmessages.CMsgVoiceAudio, Netmessages.CMsgVoiceAudio.Builder, Netmessages.CMsgVoiceAudioOrBuilder> 
          getAudioFieldBuilder() {
        if (audioBuilder_ == null) {
          audioBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Netmessages.CMsgVoiceAudio, Netmessages.CMsgVoiceAudio.Builder, Netmessages.CMsgVoiceAudioOrBuilder>(
                  getAudio(),
                  getParentForChildren(),
                  isClean());
          audio_ = null;
        }
        return audioBuilder_;
      }

      private int broadcastGroup_ ;
      /**
       * <code>optional uint32 broadcast_group = 2;</code>
       */
      public boolean hasBroadcastGroup() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 broadcast_group = 2;</code>
       */
      public int getBroadcastGroup() {
        return broadcastGroup_;
      }
      /**
       * <code>optional uint32 broadcast_group = 2;</code>
       */
      public Builder setBroadcastGroup(int value) {
        bitField0_ |= 0x00000002;
        broadcastGroup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 broadcast_group = 2;</code>
       */
      public Builder clearBroadcastGroup() {
        bitField0_ = (bitField0_ & ~0x00000002);
        broadcastGroup_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CP2P_Voice)
    }

    // @@protoc_insertion_point(class_scope:CP2P_Voice)
    private static final CPeer2PeerNetmessages.CP2P_Voice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CPeer2PeerNetmessages.CP2P_Voice();
    }

    public static CPeer2PeerNetmessages.CP2P_Voice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CP2P_Voice>
        PARSER = new com.google.protobuf.AbstractParser<CP2P_Voice>() {
      public CP2P_Voice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CP2P_Voice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CP2P_Voice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CP2P_Voice> getParserForType() {
      return PARSER;
    }

    public CPeer2PeerNetmessages.CP2P_Voice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CP2P_PingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CP2P_Ping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 send_time = 1;</code>
     */
    boolean hasSendTime();
    /**
     * <code>required uint64 send_time = 1;</code>
     */
    long getSendTime();

    /**
     * <code>required bool is_reply = 2;</code>
     */
    boolean hasIsReply();
    /**
     * <code>required bool is_reply = 2;</code>
     */
    boolean getIsReply();
  }
  /**
   * Protobuf type {@code CP2P_Ping}
   */
  public  static final class CP2P_Ping extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CP2P_Ping)
      CP2P_PingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CP2P_Ping.newBuilder() to construct.
    private CP2P_Ping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CP2P_Ping() {
      sendTime_ = 0L;
      isReply_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CP2P_Ping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sendTime_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isReply_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CPeer2PeerNetmessages.internal_static_CP2P_Ping_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CPeer2PeerNetmessages.internal_static_CP2P_Ping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CPeer2PeerNetmessages.CP2P_Ping.class, CPeer2PeerNetmessages.CP2P_Ping.Builder.class);
    }

    private int bitField0_;
    public static final int SEND_TIME_FIELD_NUMBER = 1;
    private long sendTime_;
    /**
     * <code>required uint64 send_time = 1;</code>
     */
    public boolean hasSendTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 send_time = 1;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    public static final int IS_REPLY_FIELD_NUMBER = 2;
    private boolean isReply_;
    /**
     * <code>required bool is_reply = 2;</code>
     */
    public boolean hasIsReply() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool is_reply = 2;</code>
     */
    public boolean getIsReply() {
      return isReply_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSendTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsReply()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, sendTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isReply_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, sendTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isReply_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CPeer2PeerNetmessages.CP2P_Ping)) {
        return super.equals(obj);
      }
      CPeer2PeerNetmessages.CP2P_Ping other = (CPeer2PeerNetmessages.CP2P_Ping) obj;

      boolean result = true;
      result = result && (hasSendTime() == other.hasSendTime());
      if (hasSendTime()) {
        result = result && (getSendTime()
            == other.getSendTime());
      }
      result = result && (hasIsReply() == other.hasIsReply());
      if (hasIsReply()) {
        result = result && (getIsReply()
            == other.getIsReply());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSendTime()) {
        hash = (37 * hash) + SEND_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSendTime());
      }
      if (hasIsReply()) {
        hash = (37 * hash) + IS_REPLY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsReply());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPeer2PeerNetmessages.CP2P_Ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CPeer2PeerNetmessages.CP2P_Ping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CP2P_Ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CP2P_Ping)
        CPeer2PeerNetmessages.CP2P_PingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CPeer2PeerNetmessages.internal_static_CP2P_Ping_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CPeer2PeerNetmessages.internal_static_CP2P_Ping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CPeer2PeerNetmessages.CP2P_Ping.class, CPeer2PeerNetmessages.CP2P_Ping.Builder.class);
      }

      // Construct using CPeer2PeerNetmessages.CP2P_Ping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sendTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        isReply_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CPeer2PeerNetmessages.internal_static_CP2P_Ping_descriptor;
      }

      public CPeer2PeerNetmessages.CP2P_Ping getDefaultInstanceForType() {
        return CPeer2PeerNetmessages.CP2P_Ping.getDefaultInstance();
      }

      public CPeer2PeerNetmessages.CP2P_Ping build() {
        CPeer2PeerNetmessages.CP2P_Ping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CPeer2PeerNetmessages.CP2P_Ping buildPartial() {
        CPeer2PeerNetmessages.CP2P_Ping result = new CPeer2PeerNetmessages.CP2P_Ping(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sendTime_ = sendTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isReply_ = isReply_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CPeer2PeerNetmessages.CP2P_Ping) {
          return mergeFrom((CPeer2PeerNetmessages.CP2P_Ping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CPeer2PeerNetmessages.CP2P_Ping other) {
        if (other == CPeer2PeerNetmessages.CP2P_Ping.getDefaultInstance()) return this;
        if (other.hasSendTime()) {
          setSendTime(other.getSendTime());
        }
        if (other.hasIsReply()) {
          setIsReply(other.getIsReply());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSendTime()) {
          return false;
        }
        if (!hasIsReply()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CPeer2PeerNetmessages.CP2P_Ping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CPeer2PeerNetmessages.CP2P_Ping) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long sendTime_ ;
      /**
       * <code>required uint64 send_time = 1;</code>
       */
      public boolean hasSendTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 send_time = 1;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>required uint64 send_time = 1;</code>
       */
      public Builder setSendTime(long value) {
        bitField0_ |= 0x00000001;
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 send_time = 1;</code>
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendTime_ = 0L;
        onChanged();
        return this;
      }

      private boolean isReply_ ;
      /**
       * <code>required bool is_reply = 2;</code>
       */
      public boolean hasIsReply() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool is_reply = 2;</code>
       */
      public boolean getIsReply() {
        return isReply_;
      }
      /**
       * <code>required bool is_reply = 2;</code>
       */
      public Builder setIsReply(boolean value) {
        bitField0_ |= 0x00000002;
        isReply_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool is_reply = 2;</code>
       */
      public Builder clearIsReply() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isReply_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CP2P_Ping)
    }

    // @@protoc_insertion_point(class_scope:CP2P_Ping)
    private static final CPeer2PeerNetmessages.CP2P_Ping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CPeer2PeerNetmessages.CP2P_Ping();
    }

    public static CPeer2PeerNetmessages.CP2P_Ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CP2P_Ping>
        PARSER = new com.google.protobuf.AbstractParser<CP2P_Ping>() {
      public CP2P_Ping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CP2P_Ping(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CP2P_Ping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CP2P_Ping> getParserForType() {
      return PARSER;
    }

    public CPeer2PeerNetmessages.CP2P_Ping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CP2P_TextMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CP2P_TextMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CSteam_Voice_Encoding_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CSteam_Voice_Encoding_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CP2P_Voice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CP2P_Voice_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CP2P_Ping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CP2P_Ping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035c_peer2peer_netmessages.proto\032\021netmess" +
      "ages.proto\" \n\020CP2P_TextMessage\022\014\n\004text\030\001" +
      " \001(\014\"+\n\025CSteam_Voice_Encoding\022\022\n\nvoice_d" +
      "ata\030\001 \001(\014\"h\n\nCP2P_Voice\022\036\n\005audio\030\001 \001(\0132\017" +
      ".CMsgVoiceAudio\022\027\n\017broadcast_group\030\002 \001(\r" +
      "\"!\n\rHandler_Flags\022\020\n\014Played_Audio\020\001\"0\n\tC" +
      "P2P_Ping\022\021\n\tsend_time\030\001 \002(\004\022\020\n\010is_reply\030" +
      "\002 \002(\010*C\n\014P2P_Messages\022\024\n\017p2p_TextMessage" +
      "\020\200\002\022\016\n\tp2p_Voice\020\201\002\022\r\n\010p2p_Ping\020\202\002B\003\200\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Netmessages.getDescriptor(),
        }, assigner);
    internal_static_CP2P_TextMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CP2P_TextMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CP2P_TextMessage_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_CSteam_Voice_Encoding_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CSteam_Voice_Encoding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CSteam_Voice_Encoding_descriptor,
        new java.lang.String[] { "VoiceData", });
    internal_static_CP2P_Voice_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CP2P_Voice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CP2P_Voice_descriptor,
        new java.lang.String[] { "Audio", "BroadcastGroup", });
    internal_static_CP2P_Ping_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CP2P_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CP2P_Ping_descriptor,
        new java.lang.String[] { "SendTime", "IsReply", });
    Netmessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
