package pv.dotai.datai.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_oauth.steamworkssdk.proto

public final class SteammessagesOauthSteamworkssdk {
  private SteammessagesOauthSteamworkssdk() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface COAuthToken_ImplicitGrantNoPrompt_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:COAuthToken_ImplicitGrantNoPrompt_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
     */
    boolean hasClientid();
    /**
     * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
     */
    java.lang.String getClientid();
    /**
     * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
     */
    com.google.protobuf.ByteString
        getClientidBytes();
  }
  /**
   * Protobuf type {@code COAuthToken_ImplicitGrantNoPrompt_Request}
   */
  public  static final class COAuthToken_ImplicitGrantNoPrompt_Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:COAuthToken_ImplicitGrantNoPrompt_Request)
      COAuthToken_ImplicitGrantNoPrompt_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use COAuthToken_ImplicitGrantNoPrompt_Request.newBuilder() to construct.
    private COAuthToken_ImplicitGrantNoPrompt_Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private COAuthToken_ImplicitGrantNoPrompt_Request() {
      clientid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private COAuthToken_ImplicitGrantNoPrompt_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              clientid_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request.class, SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request.Builder.class);
    }

    private int bitField0_;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientid_;
    /**
     * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
     */
    public boolean hasClientid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
     */
    public java.lang.String getClientid() {
      java.lang.Object ref = clientid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
     */
    public com.google.protobuf.ByteString
        getClientidBytes() {
      java.lang.Object ref = clientid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request)) {
        return super.equals(obj);
      }
      SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request other = (SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request) obj;

      boolean result = true;
      result = result && (hasClientid() == other.hasClientid());
      if (hasClientid()) {
        result = result && getClientid()
            .equals(other.getClientid());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasClientid()) {
        hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
        hash = (53 * hash) + getClientid().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code COAuthToken_ImplicitGrantNoPrompt_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:COAuthToken_ImplicitGrantNoPrompt_Request)
        SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request.class, SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request.Builder.class);
      }

      // Construct using SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_descriptor;
      }

      public SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request getDefaultInstanceForType() {
        return SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request.getDefaultInstance();
      }

      public SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request build() {
        SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request buildPartial() {
        SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request result = new SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientid_ = clientid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request) {
          return mergeFrom((SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request other) {
        if (other == SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request.getDefaultInstance()) return this;
        if (other.hasClientid()) {
          bitField0_ |= 0x00000001;
          clientid_ = other.clientid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object clientid_ = "";
      /**
       * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
       */
      public boolean hasClientid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
       */
      public java.lang.String getClientid() {
        java.lang.Object ref = clientid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
       */
      public com.google.protobuf.ByteString
          getClientidBytes() {
        java.lang.Object ref = clientid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
       */
      public Builder setClientid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
       */
      public Builder clearClientid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientid_ = getDefaultInstance().getClientid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientid = 1 [(.description) = "Client ID for which to count the number of issued tokens"];</code>
       */
      public Builder setClientidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:COAuthToken_ImplicitGrantNoPrompt_Request)
    }

    // @@protoc_insertion_point(class_scope:COAuthToken_ImplicitGrantNoPrompt_Request)
    private static final SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request();
    }

    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<COAuthToken_ImplicitGrantNoPrompt_Request>
        PARSER = new com.google.protobuf.AbstractParser<COAuthToken_ImplicitGrantNoPrompt_Request>() {
      public COAuthToken_ImplicitGrantNoPrompt_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new COAuthToken_ImplicitGrantNoPrompt_Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<COAuthToken_ImplicitGrantNoPrompt_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<COAuthToken_ImplicitGrantNoPrompt_Request> getParserForType() {
      return PARSER;
    }

    public SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface COAuthToken_ImplicitGrantNoPrompt_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:COAuthToken_ImplicitGrantNoPrompt_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
     */
    boolean hasAccessToken();
    /**
     * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
     */
    java.lang.String getAccessToken();
    /**
     * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
     */
    boolean hasRedirectUri();
    /**
     * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
     */
    java.lang.String getRedirectUri();
    /**
     * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
     */
    com.google.protobuf.ByteString
        getRedirectUriBytes();
  }
  /**
   * Protobuf type {@code COAuthToken_ImplicitGrantNoPrompt_Response}
   */
  public  static final class COAuthToken_ImplicitGrantNoPrompt_Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:COAuthToken_ImplicitGrantNoPrompt_Response)
      COAuthToken_ImplicitGrantNoPrompt_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use COAuthToken_ImplicitGrantNoPrompt_Response.newBuilder() to construct.
    private COAuthToken_ImplicitGrantNoPrompt_Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private COAuthToken_ImplicitGrantNoPrompt_Response() {
      accessToken_ = "";
      redirectUri_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private COAuthToken_ImplicitGrantNoPrompt_Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              accessToken_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              redirectUri_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response.class, SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response.Builder.class);
    }

    private int bitField0_;
    public static final int ACCESS_TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
     */
    public boolean hasAccessToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
     */
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accessToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REDIRECT_URI_FIELD_NUMBER = 2;
    private volatile java.lang.Object redirectUri_;
    /**
     * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
     */
    public boolean hasRedirectUri() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
     */
    public java.lang.String getRedirectUri() {
      java.lang.Object ref = redirectUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          redirectUri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
     */
    public com.google.protobuf.ByteString
        getRedirectUriBytes() {
      java.lang.Object ref = redirectUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirectUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, redirectUri_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessToken_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, redirectUri_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response)) {
        return super.equals(obj);
      }
      SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response other = (SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response) obj;

      boolean result = true;
      result = result && (hasAccessToken() == other.hasAccessToken());
      if (hasAccessToken()) {
        result = result && getAccessToken()
            .equals(other.getAccessToken());
      }
      result = result && (hasRedirectUri() == other.hasRedirectUri());
      if (hasRedirectUri()) {
        result = result && getRedirectUri()
            .equals(other.getRedirectUri());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAccessToken()) {
        hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getAccessToken().hashCode();
      }
      if (hasRedirectUri()) {
        hash = (37 * hash) + REDIRECT_URI_FIELD_NUMBER;
        hash = (53 * hash) + getRedirectUri().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code COAuthToken_ImplicitGrantNoPrompt_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:COAuthToken_ImplicitGrantNoPrompt_Response)
        SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response.class, SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response.Builder.class);
      }

      // Construct using SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        accessToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        redirectUri_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesOauthSteamworkssdk.internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_descriptor;
      }

      public SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response getDefaultInstanceForType() {
        return SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response.getDefaultInstance();
      }

      public SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response build() {
        SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response buildPartial() {
        SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response result = new SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accessToken_ = accessToken_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.redirectUri_ = redirectUri_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response) {
          return mergeFrom((SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response other) {
        if (other == SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response.getDefaultInstance()) return this;
        if (other.hasAccessToken()) {
          bitField0_ |= 0x00000001;
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (other.hasRedirectUri()) {
          bitField0_ |= 0x00000002;
          redirectUri_ = other.redirectUri_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object accessToken_ = "";
      /**
       * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
       */
      public boolean hasAccessToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accessToken_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
       */
      public Builder clearAccessToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string access_token = 1 [(.description) = "OAuth Token, granted on success"];</code>
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accessToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object redirectUri_ = "";
      /**
       * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
       */
      public boolean hasRedirectUri() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
       */
      public java.lang.String getRedirectUri() {
        java.lang.Object ref = redirectUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            redirectUri_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
       */
      public com.google.protobuf.ByteString
          getRedirectUriBytes() {
        java.lang.Object ref = redirectUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          redirectUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
       */
      public Builder setRedirectUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        redirectUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
       */
      public Builder clearRedirectUri() {
        bitField0_ = (bitField0_ & ~0x00000002);
        redirectUri_ = getDefaultInstance().getRedirectUri();
        onChanged();
        return this;
      }
      /**
       * <code>optional string redirect_uri = 2 [(.description) = "Redirection URI provided during client registration."];</code>
       */
      public Builder setRedirectUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        redirectUri_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:COAuthToken_ImplicitGrantNoPrompt_Response)
    }

    // @@protoc_insertion_point(class_scope:COAuthToken_ImplicitGrantNoPrompt_Response)
    private static final SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response();
    }

    public static SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<COAuthToken_ImplicitGrantNoPrompt_Response>
        PARSER = new com.google.protobuf.AbstractParser<COAuthToken_ImplicitGrantNoPrompt_Response>() {
      public COAuthToken_ImplicitGrantNoPrompt_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new COAuthToken_ImplicitGrantNoPrompt_Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<COAuthToken_ImplicitGrantNoPrompt_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<COAuthToken_ImplicitGrantNoPrompt_Response> getParserForType() {
      return PARSER;
    }

    public SteammessagesOauthSteamworkssdk.COAuthToken_ImplicitGrantNoPrompt_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'steammessages_oauth.steamworkssdk.prot" +
      "o\032.steammessages_unified_base.steamworks" +
      "sdk.proto\"{\n)COAuthToken_ImplicitGrantNo" +
      "Prompt_Request\022N\n\010clientid\030\001 \001(\tB<\202\265\0308Cl" +
      "ient ID for which to count the number of" +
      " issued tokens\"\267\001\n*COAuthToken_ImplicitG" +
      "rantNoPrompt_Response\0229\n\014access_token\030\001 " +
      "\001(\tB#\202\265\030\037OAuth Token, granted on success" +
      "\022N\n\014redirect_uri\030\002 \001(\tB8\202\265\0304Redirection " +
      "URI provided during client registration.",
      "2\261\002\n\nOAuthToken\022\353\001\n\025ImplicitGrantNoPromp" +
      "t\022*.COAuthToken_ImplicitGrantNoPrompt_Re" +
      "quest\032+.COAuthToken_ImplicitGrantNoPromp" +
      "t_Response\"y\202\265\030uGrants an implicit OAuth" +
      " token (grant type \'token\') for the spec" +
      "ified client ID on behalf of a user with" +
      "out prompting\0325\202\265\0301Service containing me" +
      "thods to manage OAuth tokens"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesUnifiedBaseSteamworkssdk.getDescriptor(),
        }, assigner);
    internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_COAuthToken_ImplicitGrantNoPrompt_Request_descriptor,
        new java.lang.String[] { "Clientid", });
    internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_COAuthToken_ImplicitGrantNoPrompt_Response_descriptor,
        new java.lang.String[] { "AccessToken", "RedirectUri", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamworkssdk.description);
    registry.add(SteammessagesUnifiedBaseSteamworkssdk.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamworkssdk.serviceDescription);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesUnifiedBaseSteamworkssdk.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
